dist: xenial
sudo: required
language: java
# notifications:
#   slack:
#     secure: c8TGIgFUIwQm/b4LKRjyqs+Lw4QCg2nd6lnwxjwsJKCJBUmJp5Pf+h8rznXJUglxytYWoLZQ7NFuFyt85L1RQQxK+rWeRn6mddEr5gR3vXJUvYycPAIWDGfVVkSsKdPVyxgbmlrSxbThB4lMHIeUUzE4ITTb9IyXxPcvTHSBPQVpED/MlJgYLucRKHpUbvNn8Bj+bKECDzbNoZTLc7gXDPIi3ejazLC2BYzxHfk52b7O18LhLMWVra8fccxlr1sBzprrzTKj10yDXrzuyv8YOcFTs/ru8wZyz+8hPk97KBk1wyEN7mFhFVPlTQP/cOMYUMM/iflWLV2iR0gmg7Y5LrBauR0CkLW30KOLR9p4B4Ygp5CuJPxrniYfKUXlB1KyUPLlDjMc8/CZ8Aunc4SniZqDg8Ow4vix/3PebGj+2rwjDL7KizMzxNSQa0ieMEUxgiWnPl5ZY8zXUkklHH+x7sB9aX3UpElnfREbq9d9w2Ak6EwvANTds4lPScieOY1gntvTCfcEethR3mMEY9vT4R9+ZXF54RKogbBFG89k+1J2Dv0rI8ZZTpwYIkNWHpxfIeKz4jekOm0lFJE/8/zWIgyZEZSqIi6GhfiFaEUzOKXG295VfDhE5KF+uzXVHeWPA8Hgy1aggCtXc/hBam3L8Ec2gaSEU547MNuLOMQkEhY=
jdk:
# - openjdk8
- openjdk11
services:
- docker
before_install:
- gem install asciidoctor
install:
- mvn -q install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- "./.travis/install_yq.sh"
- "./.travis/setup-kubernetes.sh"
script:
- "./.travis/build.sh"
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - COMMIT=${TRAVIS_COMMIT::8}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-master}
  - DOCKER_ORG=leeyanzhe
  - DOCKER_REGISTRY=docker.io
  - TEST_CLUSTER=minikube
  - TEST_KUBECTL_VERSION=v1.15.0
  - TEST_NSENTER_VERSION=2.32
  - TEST_HELM_VERSION=v2.9.1
  - TEST_MINIKUBE_VERSION=v1.2.0
  - STRIMZI_DEFAULT_LOG_LEVEL=DEBUG
  - MVN_ARGS="-q"
  - DOCKER_BUILD_ARGS="-q"
  - secure: P5WhKnwVmilleI/9KDUn+/7ygfi86G4Y+xS6JM5Odzvy51kfMKYnDe+HJr6sF7q1IkPzJE50g5yUA3pInp08CHHFHIjJ+vS8rlVY6Lw9QRPzBFCGvwJlgawZZvZ+OWBYYNOXyVhVikmVouJMiqgK0mxp+/h5Y3bGYWlSXB5S0CjsbzlZdcdvgYonzJDxWLhnx6CVdGHOXsFRFA2B9aLHwzLZHwdcUXHJ7nwfDp6G1fqgkQRKDfwZCoTIAVBaW/AdiQOmvK/v+LMpsZoXV4UaRNy4eVKzIasfSEAc+ZVCTCzXB2QPiPpQZSTtBXykAGNV8Q6cfS9cC/yKBYBuTI/oCjkEwQPsffD2+ubJwJko63jP0b+woe89Aiclqgxq19OoGaenCpSTpWL1G3kEipY9fhBcE9OzqoQA9f4vvIETrsSD7ldhAJizZ1w2ctGrMlwfCsjT6b/W3Hm3m9F1RYdHK16bUwMgoKBp47hGQDnMg/FJE7UbM1gNJ2/ejnQi4rb0G/OMiXI6M/e6oPjVe+S+MmoyrTgEBsK71TAFm3UKsUmALtPHPBnX582FXABkygNCb+KcLf9d1EVAjdA3SkMpeYpfydaiKdcrKtA6zWoUF/lkY+5F0KfiRIxnSc1mpnh/jiCeBd8DHehuI0rK4aIlPcGWESGURFjfoGRD9RT6+6g= # DOCKER_USER
  - secure: RiBq2D3DqP/94s2ODBu0iv8IpJNKV+pW6O1JnSvBwpNqcgitUfofJA7bBkHOxUFvyK++mFbl7mZ8LP54awFOSGoUnExBkYY2vhxVo+IQSgD6gPJxPbeYD4+DOJU4avnSPSwJgmAex6dIyk6RL5D/YoArO0EGNdAEntHsC28QA1CNB1tcYerBj7QbEuT0NfeV7rqbEks5E38Wbp7M4zeitfhl4PF9Kdojf68ELCAfIEmvQxa1HfpXK7SEsRutm4iVgwYdS3K4Eqi1zXV3lLoDhqVR3+9kax3I+tz6xetvuuAzzLofYU/TTTzSV+vva/qR2uFk4aB579p6rQUzajUyiSTV/H/vDzPFhek7hCjjTlMNaCt0Xt9jLgh4Snh4zqvs+k3aw2Vwrapl0RQYCHfJYFeSbKUdb/y+XorPlm9yTxebhJ/S6DRh3DXyTjNMy1I80o9Ssq2Y1VX2PT7lm4pucNiwb9W03YPZI/pENSHKLFe2uEx0ZoqTmICTfWipmbHwb/hFdKivVQKMEE95EOGAVqLdpM/chRTH3oCpW7S2Sy6agSzM3H8ei4jsKZIZLEh5q6GVG5igFP47NVcfK3T0YD6rYSOfkaEreq2EJiIUsOb2kxlgznSBSiKy5I4cAdkc/cBbPuwiIv1UqiijSaoRoAolKQ8t+sBUdciSH2/yEv8= # DOCKER_PASS

